apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-tracker-deployment
spec:
  selector:
    matchLabels:
      name: money-tracker-webapi
  replicas: 2
  template:
    metadata:
      labels:
        name: money-tracker-webapi
    spec:
      containers:
        - name: money-tracker-app
          image: crfalcao.azurecr.io/money-tracker:latest
          imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default
  name: ingress-router
spec:
  rules:
  - http:
      paths:
      - path: /money-tracker(/|$)(.*)
        backend:
          serviceName: money-tracker-service
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: money-tracker-service
  labels:
    app: money-tracker
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  selector:
    name: money-tracker-webapi