// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package repositoy

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Get(ctx context.Context, id pgtype.UUID) (RawTransaction, error)
}

var _ Querier = (*Queries)(nil)
