// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RawTransaction struct {
	ID                pgtype.UUID      `db:"id" json:"id"`
	AccountID         pgtype.Text      `db:"account_id" json:"accountId"`
	DatePosted        pgtype.Timestamp `db:"date_posted" json:"datePosted"`
	TransactionAmount pgtype.Numeric   `db:"transaction_amount" json:"transactionAmount"`
	FitID             int32            `db:"fit_id" json:"fitId"`
	Checknum          string           `db:"checknum" json:"checknum"`
	Memo              string           `db:"memo" json:"memo"`
}

type User struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"createdAt"`
	Name         string           `db:"name" json:"name"`
	Email        string           `db:"email" json:"email"`
	Passwordhash string           `db:"passwordhash" json:"passwordhash"`
	Salt         string           `db:"salt" json:"salt"`
}
