// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: raw_transactions_queries.sql

package queries

import (
	"context"
)

const getRawTransaction = `-- name: GetRawTransaction :one
SELECT id, account_id, date_posted, transaction_amount, fit_id, checknum, memo FROM raw_transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRawTransaction(ctx context.Context, id int32) (RawTransaction, error) {
	row := q.db.QueryRow(ctx, getRawTransaction, id)
	var i RawTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DatePosted,
		&i.TransactionAmount,
		&i.FitID,
		&i.Checknum,
		&i.Memo,
	)
	return i, err
}
