// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const get = `-- name: Get :one
SELECT id, account_id, date_posted, transaction_amount, fit_id, checknum, memo FROM raw_transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id pgtype.UUID) (RawTransaction, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i RawTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DatePosted,
		&i.TransactionAmount,
		&i.FitID,
		&i.Checknum,
		&i.Memo,
	)
	return i, err
}
