name: Deploy
on: 
  push:
    branches: [ master, "release/*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Build and push Docker image in container registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crfalcao.azurecr.io/money-tracker
        registry: ${{ secrets.AZ_DOCKER_REGISTRY }}
        username: ${{ secrets.AZ_DOCKER_USERNAME }}
        password: ${{ secrets.AZ_DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.AZ_KUBECONFIG }}
      
      - name: Check if ingress exists
        id: ingress
        run: echo ::set-output name=ingress_exists::$(kubectl get namespaces | grep nginx-ingress | wc -l)

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.AZ_DOCKER_REGISTRY }}
          container-registry-username: ${{ secrets.AZ_DOCKER_USERNAME }}
          container-registry-password: ${{ secrets.AZ_DOCKER_PASSWORD }}
          secret-name: k8s-secret
      
      - uses: Azure/k8s-deploy@v1
        if: steps.ingress.output.ingress_exists == 0
        with:
          manifests: |
            ./.k8s/ingress-deployment.yaml
            ./.k8s/ingress-service.yaml

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            ./.k8s/deployment.yml
            ./.k8s/ingress-resources.yaml
          images: |
            crfalcao.azurecr.io/money-tracker:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret
