name: Deploy
on: 
  push:
    branches: [ master, "release/*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Build and push Docker image
      uses: kciter/aws-ecr-action@v1
      with:
        repo: money-tracker
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        region: us-east-2
        tags: latest,${{ github.sha }}
        create_repo: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: export IngressNamespaceExists=`kubectl get namespaces | grep -c ingress-nginx`
      
      - uses: actions/kubectl@master
          if: IngressNamespaceExists == 0
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "Creating Ingress service."
          kubectl apply -f ./.k8s/ingress-deployment.yaml
          kubectl apply -f ./.k8s/ingress-service.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/deployment.yml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/ingress-resources.yml

