name: Deploy
on: 
  push:
    branches: [ master, "release/*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Build and push Docker image
      uses: kciter/aws-ecr-action@v1
      with:
        repo: money-tracker
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        region: us-east-2
        tags: latest,${{ github.sha }}
        create_repo: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Get nginx-ingress kubernetes namespace
        id: ingress-namespace-check
        uses: Consensys/kubernetes-action@master
        with:
          args: get namespaces | grep ingress-nginx
      
      - name: Creating Ingress deployment
        if: ${{ !steps.ingress-namespace-check.outputs.result }}
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/ingress-deployment.yaml
          
      - name: Creating Ingress Service
        if: ${{ !steps.ingress-namespace-check.outputs.result }}
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/ingress-service.yaml

      - name: Applying the application deployment
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/deployment.yml
      
      - name: Appying the ingress resources configuration
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./.k8s/ingress-resources.yml

