name: Docker

on:
  push:
    branches: [ master, "release/*" ]

jobs:
  build:
        # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check out code

      - uses: elgohr/Publish-Docker-Github-Action@master
      - name: Build and push Docker image
      with:
        image: eduardocfalcao/money-tracker
        tag: latest
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
